licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

load("//tensorflow_addons:tensorflow_addons.bzl", "addon_cc_library")

addon_cc_library(
    name = "concat_inputs",
    srcs = ["concat_inputs_ops.cc", "concat_inputs_ops.h"],
    deps = []
)