licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

load("//tensorflow_addons:tensorflow_addons.bzl", "addon_cc_library")

addon_cc_library(
    name = "gather_indice_value",
    srcs = ["gather_indice_value_ops.cc", "gather_indice_value_ops.h"],
    deps = []
)
